LawOfficeAdvertisement/Models/ErrorViewModel.cs
namespace LawOfficeAdvertisement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LawOfficeAdvertisement/Models/SavaTest1.cs
namespace LawOfficeAdvertisement.Models
{
    public class SavaTest1
    {
    }
}

LawOfficeAdvertisement/Models/SavaTest2.cs
namespace LawOfficeAdvertisement.Models
{
    public class SavaTest2
    {
    }
}

LawOfficeAdvertisement/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace LawOfficeAdvertisement.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult ListOfAllActivities()
        {
            return View();
        }
        public IActionResult AdministrativnoPravo()
        {
            return View();
        }

        public IActionResult KorporativnoPravo()
        {
            return View();
        }

        public IActionResult NakazatelnoPravo()
        {
            return View();
        }
        public IActionResult NesastoyatelnostLikvidaciya()
        {
            return View();
        }
        public IActionResult ObligacionnoPravo()
        {
            return View();
        }
        public IActionResult ProcesualnoPredstavitelstvo()
        {
            return View();
        }
        public IActionResult SemeynoNasledstvenoPravo()
        {
            return View();
        }
        public IActionResult TargovskoPravo()
        {
            return View();
        }
        public IActionResult VeshtnoPravo()
        {
            return View();
        }
    }
}

LawOfficeAdvertisement/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace LawOfficeAdvertisement.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LawOfficeAdvertisement/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace LawOfficeAdvertisement.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Contacts()
        {
            return View();
        }
    }
}

LawOfficeAdvertisement/Controllers/HomeController.cs
using LawOfficeAdvertisement.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LawOfficeAdvertisement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LawOfficeAdvertisement/Controllers/LawsController.cs
using Microsoft.AspNetCore.Mvc;

namespace LawOfficeAdvertisement.Controllers
{
    public class LawsController : Controller
    {
        
    }
}

LawOfficeAdvertisement/Views/AboutUs/AdministrativnoPravo.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Административно право и процес</h1></center>
                <hr />
                <p>
                    &nbsp;&nbsp;Кантората представлява клиентите си пред административните органи във връзка с издаването на съответните разрешителни и лицензии, необходими за създаване и управляване на разнородни бизнеси в България. Екипът ни изготвя пакети документи или консултира клиентите във връзка с административните процедури, като анализът на документите включва, както проверка за съответствие с българското законодателство, така и комплексно изследване на правните последици и препоръки за избор на действия, които в най - голяма степен ще съответстват на стопанските интереси на клиентите ни.
                </p>
                <p>
                    &nbsp;&nbsp;Практиката ни включва широк кръг от административни процедури - от временно или постоянно пребиваване на чуждестранни граждани на територията на Република България, придобиване, възстановяване и отказ от българско гражданство до защита интересите на клиентите ни пред различни регулаторни органи - Комисията за защита на конкуренцията, Комисията по търговия и защита на потребителите и др.
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/KorporativnoPravo.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Корпоративно право</h1></center>
                <hr />
                <p>Кантората е специализирана в областта на:</p>
                <p>
                    <ul>
                        <li>Учредяване на дружества;</li>
                        <li>Текущи правни услуги за дружествата и техния правен статус;</li>
                        <li>Чуждестранни инвестиции (включително услуги, свързани с поддържане статуса на инвестиционния проект);</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/ListOfAllActivities.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <ul>
                    <center><h1>Услуги на адвокат Шаренков</h1></center>
                    <hr />
                    <p>
                        Дейността на адвокат Шаренков се простира върху различни области на процесуалното представителство. Той е утвърден и предпочитан, като представител и консултант при:
                    </p>


                </ul>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/NakazatelnoPravo.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Наказателно право</h1></center>
                <hr />
                <p>
                    <ul>
                        <li>Специализирана правна помощ на пострадали при ПТП.</li>
                        <li>Консултации и становища по наказателни дела;</li>
                        <li>Процесуално представителство пред съд по Мярка за неотклонение.</li>
                        <li>Правна помощ и защита по досъдебни производства;</li>
                        <li>Съдебна защита по наказателни дела (първа инстанция, въззивна инстанция и пред ВКС);</li>
                        <li>Съдействие за постигане на споразумения по дела /за алкохол и др/.</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/NesastoyatelnostLikvidaciya.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Несъстоятелност и ликвидация</h1></center>
                <hr />
                <p>
                    &nbsp;&nbsp;Кантората  ни предоставя консултации и правна помощ при проблеми, свързани с търговската несъстоятелност. Оказваме правна защита при откриване на производство по несъстоятелност при изготвяне и подаване на молби за откриване на производство по несъстоятелност пред съд, по време на самото производство; представителство на кредитори в производството по несъстоятелност, при преговори между кредитори на неплатежоспособни дружества, при консултиране на управители  относно задълженията им, свързани с дружества в несъстоятелност и представляваме клиентите си във всички фази на процеса.
                </p>
                <p>
                    &nbsp;&nbsp;Притежаваме ценен опит в ликвидацията на търговски  дружества, предоставяйки правни съвети и представителство на клиентите ни пред Национална агенция за приходите,Националния осигурителен институт  и други компетентни институции във връзка с разпределяне на имуществото на ликвидиращо се дружество между кредиторите и издаването на различни удостоверения, необходими за представяне в Търговски регистър при заличаване на дружеството.
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/ObligacionnoPravo.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Облигационно право</h1></center>
                <hr />
                <p>Предлагани услуги и дейност:</p>
                <p>
                    <ul>
                        <li>Kонсултации във връзка с преддоговорни отношения, сключване, изменение, изпълнение, прекратяване на договори.</li>
                        <li>Oбезщетения и неустойки.</li>
                        <li>Изготвяне на всички видове облигационни договори – покупко-продажба, заем, наем, договор за придобиване на имот срещу задължение за издръжка и гледане, дарение, замяна.</li>
                        <li>Правно консултиране, проучване на собствеността, посредничество при търсене на недвижими имоти, изготвяне на предварителни договори и нотариални актове.</li>
                        <li>Оказване на съдействие пред нотариус.</li>
                        <li>Изготвяне на договори за покупко-продажба на МПС и съдействие пред нотариус.</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/AboutUs/ProcesualnoPredstavitelstvo.cshtml
<div class="container p-4" id="praktikaDiv">
    <div class="row">
        <div class="col-lg-3 col-md-12 mb-4 mb-md-0">
            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="AdministrativnoPravo">Административно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="KorporativnoPravo">Корпоративно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="TargovskoPravo">Търговско право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="VeshtnoPravo">Вещно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ObligacionnoPravo">Облигационно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NakazatelnoPravo">Наказателно право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="SemeynoNasledstvenoPravo">Семейно и наследствено право</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="NesastoyatelnostLikvidaciya">Несъстоятелност и ликвидация</a>
            </div>

            <div class="six col">
                <a class="button" id="button-16" asp-controller="AboutUs" asp-action="ProcesualnoPredstavitelstvo">Процесуално представителство</a>
            </div>
        </div>
        <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
            <div class="text_box">
                <center><h1>Процесуално представителство и разрешаване на спорове</h1></center>
                <hr />
                <p>
                    &nbsp;&nbsp;Кантората е привърженик  на превенцията, а не на съдебния спор, затова се стремим да допринесем за извънсъдебно разрешаване на възникнали спорове - чрез преговори, доброволно изпълнение, споразумения, алтернативни начини за разрешаване на спорове. Въпреки стремежът ни за избягване на съдебни процеси, когато договорните отношения на клиентите ни са се развили по начин, който води до явяване в съдебен процес, когато са нарушени или застрашени  права или законни интереси на клиентите, ние сме в постоянна готовност да ги защитаваме във всички инстанции на производството.
                </p>
                <p>
                    &nbsp;&nbsp;Кантората представлява клиентите си и пред арбитражните съдилища в България, консултираме ги по отношение арбитражните клаузи в договорите им, изготвяме извънсъдебни споразумения.
                </p>
                <p>
                    &nbsp;&nbsp;Екипът на кантората ни има опит във всички сфери на гражданското съдопроизводство - граждански, търговски, трудови, данъчни и други административни дела, производства за допускане на изпълнение в България на чуждестранни  решения. След успешно приключване на съдебния процес съдействаме при въвеждане в изпълнение на решението до пълното удовлетворяване интереса на  клиента.
                </p>
            </div>
        </div>
    </div>
</div>

LawOfficeAdvertisement/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Blog Page";
}

<div class="text-center">
    <h1 class="display-4">Блогът е временно недостъпен.</h1>
    <p><img class="picture-1" src="~/img/settings1.png"></p>
    
</div>

LawOfficeAdvertisement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LawOfficeAdvertisement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LawOfficeAdvertisement.styles.css" asp-append-version="true" />
    <!-- Load an icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header class="fixed-top">
        <div class="top-bar navbar-expand-md navbar-dark" style="background-color: #2b2b2b;">
            <div class="container-fluid">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-light" href="#"><i class="fa fa-fw fa-phone"></i> +359 898 58 40 80</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="#"><i class="fa fa-fw fa-envelope"></i> sharenkov_g@abv.bg</a>
                    </li>
                    <li class="nav-item ms-auto">
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </div>
        </div>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow bottom-border mb-3" style="background-color: #cf9e7f;">
            @*<img class="logo" src="~/img/LOGO.png"> *@
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class=logo src="~/img/nameLOGO.png"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="ListOfAllActivities">Практика</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Блог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contacts">Контакти</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footer footer-clean">
        <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-4 item">
                        <img class="logobanner" src="~/img/LOGObanner.png">
                    </div>
                    <div class="col-sm-4 col-md-4 item">
                        <h3>Адрес</h3>
                        <ul>
                            <li>ул. "Алеко Константинов" 16</li>
                            <li>ет. 3, офис. 9Б</li>
                            <li>гр. Варна, общ. Варна</li>
                            <li>9000, България</li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-4 item">
                        <h3>Контакти</h3>
                        <ul>
                            <li><i class="fa fa-fw fa-envelope me-3 text-secondary"></i> sharenkov_g@abv.bg</li>
                            <li><i class="fa fa-fw fa-phone me-3 text-secondary"></i> +359 898 58 40 80</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="text-muted text-center">
                <div class="container2" style="color: #cd9e7d">
                    &copy; 2023 - LawOfficeAdvertisement
                </div>
            </div>
        </footer>
    </div>



    @*<div class="wrapper">
        <footer class="footer text-center text-md-start text-muted" id="af">
        <section>
        <div class="container text-center text-md-start" style="color: #cd9e7d">
        <div class="row mt-3">
        <div class="col-xs-3 col-lg-4 col-xl-3 mx-auto mb-4">
        <img class="logobanner" src="~/img/LOGObanner.png">
        </div>
        <!-- Grid column -->
        <div class="col-md-3 col-md-2 col-md-2 mb-0">
        <h6 class="text-uppercase fw-bold mb-4">
        Useful links
        </h6>
        <p><a href="#!" class="text-reset">Pricing</a></p>
        <p><a href="#!" class="text-reset">Settings</a></p>
        <p><a href="#!" class="text-reset">Orders</a></p>
        </div>
        <!-- Grid column -->
        <div class="col-xs-4 col-md-3 col-md-3 mb-0">
        <h6 class="text-uppercase fw-bold mb-4">
        Contact
        </h6>
        <p><i class="fa fa-fw fa-home me-3 text-secondary"></i> New York, NY 10012, US</p>
        <p><i class="fa fa-fw fa-envelope me-3 text-secondary"></i> info@example.com</p>
        <p><i class="fa fa-fw fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
        </div>
        </div>
        </div>
        </section>
        <div class="text-muted text-center">
        <div class="container" style="color: #cd9e7d">
        &copy; 2023 - LawOfficeAdvertisement
        </div>
        </div>
        </footer>
        </div>*@



    @*    <footer class="footer text-muted text-center">
        <div class="container" style="color: #cd9e7d">
        &copy; 2023 - LawOfficeAdvertisement
        </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>